################################################################################
#   Section: Organizations
################################################################################
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: cli/peers/ordererOrganizations/trackchainer-orderer/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &TrackchainerOrg
        Name: TrackchainerOrgMSP
        ID: TrackchainerOrgMSP
        MSPDir: cli/peers/peerOrganizations/trackchainer-org/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('TrackchainerOrgMSP.admin', 'TrackchainerOrgMSP.peer', 'TrackchainerOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('TrackchainerOrgMSP.admin', 'TrackchainerOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('TrackchainerOrgMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('TrackchainerOrgMSP.peer')"
        AnchorPeers:
            - Host: trackchainer-peer
              Port: 7051

################################################################################
#   Section: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_5: true

################################################################################
#   Section: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   Section: Orderer
################################################################################
Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer0:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    EtcdRaft:
        Consenters:
        - Host: orderer0
          Port: 7050
          ClientTLSCert: cli/peers/ordererOrganizations/trackchainer-orderer/orderers/orderer0/tls/server.crt
          ServerTLSCert: cli/peers/ordererOrganizations/trackchainer-orderer/orderers/orderer0/tls/server.crt
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#   Section: Channel
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Section: Profiles
################################################################################
Profiles:
    OneOrgOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            TrackchainerConsortium:
                Organizations:
                    - *TrackchainerOrg
    OneOrgChannel:
        Consortium: TrackchainerConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *TrackchainerOrg
            Capabilities:
                <<: *ApplicationCapabilities
