#######################
# LedgerIT        #
# Author : Melvyn Tie #
#######################

################################################################################
# "OrdererOrgs" - Definition of organizations managing orderer nodes
################################################################################

OrdererOrgs:
  - Name: Orderer0
    Domain: ledgerit-orderer
    CommonName: orderer0
    Specs:
      - Hostname: orderer0
        CommonName: "{{.Hostname}}"

################################################################################
# "PeerOrgs" - Definition of organizations managing peer nodes
################################################################################

PeerOrgs:
  - Name: LedgerITOrg
    Domain: ledgerit-org
    Specs:
      - Hostname: ledgerit-peer
        CommonName: "{{.Hostname}}"
