#######################
# LedgerIT        #
# Author : Melvyn Tie #
#######################

################################################################################
# DOCKER COMPOSE YML FILE
################################################################################

################################################################################
# DEFINE DOCKER SERVICES
################################################################################

networks:
  net:

services:
  ledgerit-ca:
    container_name: ledgerit-ca
    image: ledgerit-ca
    extends:
            file: ./base/ca-base.yaml
            service: ca-base
    networks:
      - net
    ports:
      - 7054:7054

################################################################################
# DEFINE ORDERER
################################################################################

  orderer0:
    container_name: orderer0
    image: orderer0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/orderer/crypto/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/orderer/crypto/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/orderer/crypto/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/orderer/crypto/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/orderer/crypto/tls/ca.crt]
    working_dir: /orderer
    command: orderer
    networks:
      - net
    ports:
      - 7050:7050


################################################################################
# DEFINE THE PEER0
################################################################################

  ledgerit-peer:
    container_name: ledgerit-peer
    extends:
            file: ./base/peer-base.yaml
            service: peer-base
    image: ledgerit-peer
    environment:
      - CORE_PEER_ID=ledgerit-peer
      - CORE_PEER_ADDRESS=ledgerit-peer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=ledgerit-peer:7051
      - CORE_PEER_LOCALMSPID=LedgerITOrgMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - net
    depends_on:
      - orderer0
      - couchdb

################################################################################
# DEFINE THE PEER1
################################################################################
################################################################################
# DEFINE THE PEER2
################################################################################
################################################################################
# DEFINE COUCHDB
################################################################################
  couchdb:
    container_name: couchdb
    image: couchdb:3.3.3
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    networks:
      - net
    ports:
      - 5984:5984

################################################################################
# DEFINE APP
################################################################################

  web:
    container_name: web
    image: web:latest
    build:
      context: ../web
      dockerfile: Dockerfile
    environment:
        - PORT=3000
        - DOCKER_SOCKET_PATH=/host/var/run/docker.sock
        - DOCKER_CCENV_IMAGE=hyperledger/fabric-ccenv:2.5.4
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
    networks:
      - net
    depends_on:
        - orderer0
        - ledgerit-ca
        - ledgerit-peer
        - couchdb
    ports:
      - 3000:3000

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5.4
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=ledgerit-peer:7051
      - CORE_PEER_LOCALMSPID=LedgerITOrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ledgerit-org/peers/ledgerit-peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ledgerit-org/peers/ledgerit-peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ledgerit-org/peers/ledgerit-peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ledgerit-org/users/Admin@ledgerit-org/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ./cli/peers:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ../web/chaincode/src/ledgerit:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/
    networks:
      - net
    depends_on:
      - ledgerit-peer

  ledgerit-chaincode:
    container_name: ledgerit-chaincode
    build:
      context: ../web/chaincode/src/ledgerit
      dockerfile: Dockerfile
    environment:
      - CHAINCODE_SERVER_ADDRESS=0.0.0.0:9999
      - CORE_CHAINCODE_ID_NAME=${PACKAGE_ID}
    ports:
      - "9999:9999"
    networks:
      - net
